# Generated by Django 4.2.5 on 2023-09-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_remove_shopdb_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='CateogoryImages')),
            ],
        ),
    ]
