# Generated by Django 4.2.5 on 2023-10-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0005_contactdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDB',
        ),
    ]
